### PR TITLE
href -> to

### PR DESCRIPTION
**Pull request by abhinavsri360**
Consider the following changes

### CODE REVIEW

**Comment by akashraj9828** [comment]
Just to be clear are most of the changes just code prettifying? I think the only logic change was href-> to right?

**Comment by abhinavsri360** [comment]
Yes, that sums up the changes that I have done.
A slight change as well, I have removed the onBlur handler in the File Header.js which I found was redundant at that place. I also found that Header.js was working completely fine without that function embedded. So I removed that.

**Comment by abhinavsri360** [comment]
@akashraj9828 you can inspect and merge this PR if you find this fine.

**Comment by akashraj9828** [comment]
Actually there are so many changes because of prettifier I am unable to see clearly what changed. 
Can you make a PR without the prettified version. where only changing `I have removed the onBlur handler in the File Header.js ` and `href-> to` . I'll merge that. Thanks.

**Comment by abhinavsri360** [comment]
Sure I'll do that

**Pull request closed without merging**
