### PR TITLE
href -> to

### PR DESCRIPTION
**Pull request by abhinavsri360**
Consider the changes

### CODE REVIEW

**Comment by abhinavsri360** [comment]
You can merge these changes, I have removed #60 and pushed the same changes in here

**Comment by abhinavsri360** [comment]
Hey @akashraj9828 what are your views regarding 'having firebase images from contributions page on the home page?' 🤔
It's just a suggestion this is completely up to you. Let me know your valuable views.

**Comment by akashraj9828** [comment]
> 'having firebase images from contributions page on the home page?' 🤔

Do you mean having images of contibutor on homepage?

**Comment by abhinavsri360** [comment]
Yes, I mean the same

**Comment by akashraj9828** [comment]
That would clutter up the home page i guess. I have added the contributors credits on github though.

**Comment by abhinavsri360** [comment]
Yeah you are right, how about a link to this repository such that people who visit the home page can visit the Github repo and contribute to make this more enhanced and popular on Open-source
What do you think?

**Comment by abhinavsri360** [comment]
> That would clutter up the home page i guess. I have added the contributors credits on GitHub though.

I was thinking if you just add this much to the bottom of the home page i.e.,
Made with ❤️ by 
image

**Comment by akashraj9828** [comment]
> Yeah you are right, how about a link to this repository such that people who visit the home page can visit the Github repo and contribute to make this more enhanced and popular on Open-source
> What do you think?

This repo is linked on the homepage see the right top corner. Anyone can get to this repo via there.

Also there are 3 GitHub buttons on landing page that leads to this repo.

Adding more is not necessary I think.

**Comment by abhinavsri360** [comment]
🤔👀ohh yes

**Pull request merged**
